### ISSUE TITLE
Does this work for packages? 

### ISSUE THREAD

**Issue by sarimabbas** [sindresorhus/file-icon#10]
For instance, the `.textbundle` format just returns the icon for a folder. 

Do you have any suggestions for getting the icons of packages/bundles from the file path? Thank you!

Edit: it seems like calling the function with bundle ID gives the right icon. So then my question is, is there any way to get the bundle ID of the creating application from a path to a package?

**Comment by sindresorhus** [comment]
You need to first find which app is the default app to open the file type then you can use `file-icon`.

I think you could use https://github.com/karaggeorge/mac-open-with for the first step.

**Comment by sarimabbas** [comment]
Perfect, that's what I've been looking for! Thank you, I'll give it a try and report back if I have any trouble.

**Comment by sarimabbas** [comment]
It works great, thank you for your help
