### ISSUE TITLE
Option to write the icon to a directory

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/file-icon#3]
I think it would be very nice if `file-icon` was the one who wrote the file to a specified output directory. Something like this.

```js
fileIcon('Safari', {size: 64, dest: 'icons'}).then(()=> {
    pathExists.sync('Safari.png');
    //=> true
});
```

This in combination with #2 is very powerfull as you don't need to do anything else in Node. Most of the time this module will be used to retrieve the buffer and write it to a directory.

**Comment by sinchang** [comment]
I need this
